/* file containing all the main parameter for the game: 
- size of sector
- size of map
*/

const START_YEAR = 3248;

const TABLEAU_MAX_X = 16;
const TABLEAU_MAX_Y = 16;
const SECTOR_MAX_X = 10;
const SECTOR_MAX_Y = 10;
const MAX_STAR_SECTOR = 9;
const MAX_KIPICK_SECTOR = 9;

const NO_BASE = 20;
const NO_KIPICK = 200;

const KIPICK_ENERGY = 800;
const KIPICK_SHIELD = 500;
const KIPICK_TORPEDO = 3;
const KIPICK_VARIATION = 100;
const KIPICK_ENERGY_END_TURN_RATE = 0.2;
const KIPICK_ENERGY_MAX = 1300;
const KIPICK_ENERGY_TRANSFER = 50;

/* other energy by default */ 
const ENDURCI_ENERGY = 2500;
/* energy shield by default */
const ENDURCI_SHIELD = 2500;
/* number of torpedo */
const ENDURCI_TORPEDO = 12;
/* energy rate generated by turn */
const ENDURCI_ENERGY_END_TURN_RATE = 4;
/* max energy for object */
const ENDURCI_ENERGY_MAX = 6000;
/* amount of energy to be transferred in one turn */
const ENDURCI_ENERGY_TRANSFER = 250;

/* maximum amount of energy in case of collision */
const ENERGY_COLLISION = 60;
/* energy for a collision with a Torpedo */
const ENERGY_TORPEDO = 800;

const ENERGY_RADAR = 20;
const ENERGY_PROBE = 30;
const ENERGY_MOVEMENT_SECTOR = 5;
const ENERGY_MOVEMENT_TABLEAU = 15;

const TIME_PHASER = 1000;
const TIME_MOVE = 400;
const TIME_BLINK = 300;

const DAMAGE_ENGINE = 0;
const DAMAGE_PHASER = 1;
const DAMAGE_TORPEDO = 2;
const DAMAGE_LONG_RADAR = 3;
const DAMAGE_SHORT_RADAR = 4;
const DAMAGE_PROBE = 5;
const DAMAGE_CRYSTAL = 6;
const DAMAGE_MAX = 7;

const PHASER_MULTIPLICOR = 3.5;
/* move in sector before a move in a tableau */
const MOVE_SECTOR_TABLEAU = 4;
/* number of times for a blink after collision */
const BLINK_TIMES = 6;


/* get a random number */
function getRandomInt(max) {
    return Math.floor(Math.random() * max);
}

/* to have a list of status */
function makeEnum(arr){
    let obj = {};
    for (let val of arr){
        obj[val] = Symbol(val);
    }
    return Object.freeze(obj);
}

/* Status of the object */
const ObjectStatus = makeEnum(["active","frozen","destroyed"]);

const TEXT_DAMAGE_ENGINE = "Moteur luminique";
const TEXT_DAMAGE_PHASER = "Laser";
const TEXT_DAMAGE_TORPEDO = "Torpille";
const TEXT_DAMAGE_PROBE = "Sonde";
const TEXT_DAMAGE_CRYSTAL = "Crystal de régénération";
const TEXT_DAMAGE_LONG_RADAR = "Radar lointain";
const TEXT_DAMAGE_SHORT_RADAR = "Radar proche";
const TEXT_UNITIES = "unités";
const TEXT_UNITY = "unité";
const TEXT_GALACTIC_YEAR = "Année galactique";
const TEXT_COO_GLOBALE = "Coo globales";
const TEXT_COO_LOCALE = "Coo locales";
const TEXT_ALERT = "Niveau d'alerte";
const TEXT_SHIELD_RATE = "Taux de bouclier";
const TEXT_SHIELD_ENERGY = "Energie bouclier";
const TEXT_ENERGY = "Autre énergie";
const TEXT_TORPEDOES = "Torpilles";
const TEXT_TORPEDO = "Torpille";
const TEXT_REMAINING_BASE = "Bases restantes";
const TEXT_REMAINING_KIPICK = "Kipicks restants";
const TEXT_ALERT_GREEN = "verte";
const TEXT_ALERT_YELLOW = "jaune";
const TEXT_ALERT_RED = "rouge";
const TEXT_ALERT_CRITICAL = "critique";
const TEXT_DAMAGED = "endommagé(e) pour";
const TEXT_WELCOME = "Bonne chance pour votre mission";
const TEXT_PROBE = "Rapport de la sonde au ";
const TEXT_TYPE = "Type";
const TEXT_NO_KIPICK = "Aucun kipick dans ce secteur";
const TEXT_SHIELD_ERROR = "La valeur du bouclier doit être comprise entre 1 et 99%";
const TEXT_SHIELD_CHANGE = "Taux de bouclier modifié à ";
const TEXT_ENERGY_ERROR = "Pas assez d'énergie disponible pour cette action";
const TEXT_PHASER_ACTION = "Laser vers {OBJECT}, puissance reçue de ";
const TEXT_OBJECT_DESTROYED = "{OBJECT} détruit";
const TEXT_BASE_DESTROYED = "Base détruite en position ";
const TEXT_BASE_REFUEL = "Ravitaillement à partir de la base terminé"
const TEXT_DISTANCE_ERROR = "La distance doit être comprise entre 1 et 12";
const TEXT_DIRECTION_ERROR = "La direction doit être comprise entre 0° et 360°";
const TEXT_COLLISION = "Votre vaisseau est entré en collision, choc de ";
const TEXT_COLLISION_TORPEDO = "Torpille, choc de ";
const TEXT_STAR = "Etoile";
const TEXT_BASE = "Base";
const TEXT_KIPICK = "Kipick";
const TEXT_ENDURCI = "Endurci";
const TEXT_NO_TORPEDO_LEFT = "Stock de torpille épuisé";
const TEXT_SEND_TORPEDO = "lance une torpille";
const TEXT_SEND_PHASER = "utilise le laser";
const TEXT_KIPICK_MOVE = "fait un mouvement"

/* all damage text */
const TEXT_FONCTION = [
    TEXT_DAMAGE_ENGINE,
    TEXT_DAMAGE_PHASER,
    TEXT_DAMAGE_TORPEDO,
    TEXT_DAMAGE_LONG_RADAR,
    TEXT_DAMAGE_SHORT_RADAR,
    TEXT_DAMAGE_PROBE,
    TEXT_DAMAGE_CRYSTAL];
